(function($) {
    'use strict';
    
    $(document).ready(function(){
        // Locations requires data generated by shortcode
        window.map = L.map('leaflet-map', { dragging: !L.Browser.mobile, tap: false, zoomControl: false }).setView([33.5641086, -112.1946049], 10);
        window.map.scrollWheelZoom.disable();
        L.tileLayer('https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png', { maxZoom: 18 }).addTo(window.map);

        // Icon options
        var icon = L.icon({ iconUrl: path + '/img/marker-icon.png', shadowUrl: path + '/img/marker-shadow.png', iconSize: [25, 41], shadowSize: [41, 41], iconAnchor: [13, 41], shadowAnchor: [13, 41], popupAnchor: [0, -41] });

        // Loop through each locations and create a pin and popup
        var group = new L.featureGroup([]);
        locations.forEach(function(value){
            var name = value['title'];
            var description = value['description'];
            var address = value['address'];
            var phone = value['phone'];
            var link = value['link'];
            var reservations = value['opentable_id'];
            var reservations_link = (reservations.length > 0) ? '<a href="https://www.opentable.com/single.aspx?rid='+ reservations + '&restref=' + reservations + '" class="reservations" target="_blank">Reservations</a>' : '';
            var online_ordering = value['online_ordering'];
            var online_ordering_link = (online_ordering.length > 0) ? '<a href="'+ online_ordering + '" class="order-online">Order Online</a>' : '';
            var geo = value['geo'];

            // Add icon if geo coordinates exist
            if (geo != null) {
                var marker = L.marker(geo, { icon: icon }).addTo(group);
                marker.bindPopup(
                    '<ul>' +
                        '<li class="title">'+ name + '</li>' +
                        '<li class="description">'+ description + '</li>' +
                        '<li class="address">'+ address + '</li>' +
                        '<li class="phone">'+ phone + '</li>' +
                        '<li class="links">' + 
                            '<a href="'+ link + '">View More</a>' + 
                            reservations_link +
                            online_ordering_link + 
                        '</li>' +
                    '</ul>'
                );
            }
            else console.log('Locations "' + name + '" is missing custom field "geo": ' + url);
        });

        // zoom settings
        group.addTo(window.map);
        window.map.fitBounds(group.getBounds(), { padding: [4, 4], maxZoom: 16 });
        L.control.zoom({ position:'bottomright' }).addTo(window.map);

        // Update map resize when scrolling is triggered
        $(document).on('scroll', function(){ window.map.invalidateSize(); });
    });
})(jQuery);